//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberProjesi2.MultiLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Kaynak {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Kaynak() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaberProjesi2.MultiLanguage.Kaynak", typeof(Kaynak).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Giris.
        /// </summary>
        public static string Admin_Giris {
            get {
                return ResourceManager.GetString("Admin Giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnaSayfa.
        /// </summary>
        public static string AnaSayfa {
            get {
                return ResourceManager.GetString("AnaSayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dunya.
        /// </summary>
        public static string Dunya {
            get {
                return ResourceManager.GetString("Dunya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eglenceler.
        /// </summary>
        public static string Eglenceler {
            get {
                return ResourceManager.GetString("Eglenceler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matbaaci.
        /// </summary>
        public static string Matbaaci {
            get {
                return ResourceManager.GetString("Matbaaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfalar.
        /// </summary>
        public static string Sayfalar {
            get {
                return ResourceManager.GetString("Sayfalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spor.
        /// </summary>
        public static string Spor {
            get {
                return ResourceManager.GetString("Spor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String1.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknoloji.
        /// </summary>
        public static string Teknoloji {
            get {
                return ResourceManager.GetString("Teknoloji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticaret.
        /// </summary>
        public static string Ticaret {
            get {
                return ResourceManager.GetString("Ticaret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkiye.
        /// </summary>
        public static string Turkiye {
            get {
                return ResourceManager.GetString("Turkiye", resourceCulture);
            }
        }
    }
}
